SegAnnDB: supervised machine learning for interactive DNA copy number analysis

** Background, usage

Background: please read our [[http://www.ncbi.nlm.nih.gov/pubmed/24493034][Bioinformatics 2014 paper]].

Usage demos on YouTube: 
- [[https://www.youtube.com/watch?v=BuB5RNASHjU][basic labeling]] (2 min)
- [[https://www.youtube.com/watch?v=al0kk1JWsr0][zooming, labeling, and exporting high-density profiles]] (9 min)

** Installation

See [[file:INSTALL.sh]] to install on your own server, or Abhishek's [[https://abstatic.github.io/docker-segann.html][blog
post to use our docker image]].

** Testing

We use selenium webdriver for testing. To start the test suite, first
install selenium using

#+BEGIN_SRC shell-script
pip install selenium=2.53.2
#+END_SRC

Then run [[file:tests/tests.py]]

** Scripts

- [[file:server-start.sh]] runs db_recover to fix any database issues,
  then runs [[file:process_daemon.py]] to start the profile processing
  daemon, then runs [[file:learn_daemon.py]] to start the learning daemon,
  then starts the apache/production server. ([[file:start.sh]] is the analog for the testing server)
- [[file:server-stop.sh]] stops the apache/production server. 
- [[file:server-recover-restart.sh]] runs server-stop and then server-start. ([[file:recover-restart.sh]] is the analog for the testing server)
- [[file:server-reinitialize.sh]] deletes all database information, and reinitializes a fresh/new SegAnnDB. ([[file:reinitialize.sh]] is the analog for the testing server)


