[[https://travis-ci.org/tdhock/SegAnnDB][https://travis-ci.org/tdhock/SegAnnDB.png?branch=master]]

SegAnnDB: supervised machine learning for interactive DNA copy number analysis

** Background, usage

Background: please read our [[http://www.ncbi.nlm.nih.gov/pubmed/24493034][Bioinformatics 2014 paper]].

Usage demos on YouTube: 
- [[https://www.youtube.com/watch?v=BuB5RNASHjU][basic labeling]] (2 min)
- [[https://www.youtube.com/watch?v=al0kk1JWsr0][zooming, labeling, and exporting high-density profiles]] (9 min)

** Installation

See [[file:INSTALL.sh]] to install on your own server, or Abhishek's [[https://abstatic.github.io/docker-segann.html][blog
post to use our docker image]].

** Testing

We use selenium webdriver for testing. To start the test suite, first
install selenium using

#+BEGIN_SRC shell-script
pip install selenium=2.53.2
#+END_SRC

Then install Firefox, run [[file:recover-restart.sh]], and then [[file:tests/tests.py]].

If running tests on [[https://travis-ci.org/][Travis]], Google may think that the test account is being hacked and lock it, 
causing tests to fail.  To work around this do the following:

1. Login to Google from your computer using the test account (and log out all other google accounts).
2. Open https://www.google.com/accounts/DisplayUnlockCaptcha and push the button on the page.
3. Push code and/or restart the Travis build.

It is important to realize that this link provides unlimited access for 10 minutes only, so it is best to click it immediately 
prior to pushing code or running a build.


** Scripts

- [[file:server-start.sh]] runs db_recover to fix any database issues,
  then runs [[file:process_daemon.py]] to start the profile processing
  daemon, then runs [[file:learn_daemon.py]] to start the learning daemon,
  then starts the apache/production server. ([[file:start.sh]] is the analog for the testing server)
- [[file:server-stop.sh]] stops the apache/production server. 
- [[file:server-recover-restart.sh]] runs server-stop and then server-start. ([[file:recover-restart.sh]] is the analog for the testing server)
- [[file:server-reinitialize.sh]] deletes all database information, and reinitializes a fresh/new SegAnnDB. ([[file:reinitialize.sh]] is the analog for the testing server)

** Galaxy

Two tools have been developed to allow SegAnnDB to send data to Galaxy:
1. seganndb_single_profile pulls all data for a single profile.  
2. seganndb_all_profiles adds breakpoint data from all profiles uploaded by a specified user.
These two tools can be installed by placing their folders in the galaxy tools folder and adding a tool definition for them in
the tool_conf.xml file on your Galaxy installation.
